import { Download, RefreshCw, Sparkles } from "lucide-react";
import { Button } from "@/components/ui/button";
import {
  Accordion,
  AccordionContent,
  AccordionItem,
  AccordionTrigger,
} from "@/components/ui/accordion";
import { Badge } from "@/components/ui/badge";

interface Solution {
  questionNumber: number;
  topic: string;
  question?: string;
  questionText?: string;
  correctAnswer: string;
  solution: string;
  concept?: string;
  keyConcept?: string;
}

interface SolutionsResultProps {
  exam: string;
  solutions: Solution[];
  onReset: () => void;
}

// Helper to render math-friendly text with proper symbols
const MathText = ({ text, className = "" }: { text: string; className?: string }) => {
  return (
    <span 
      className={`font-math ${className}`}
      style={{ fontFamily: "'Cambria Math', 'Latin Modern Math', 'STIX Two Math', serif" }}
    >
      {text}
    </span>
  );
};

const SolutionsResult = ({ exam, solutions, onReset }: SolutionsResultProps) => {
  const handleDownloadPdf = () => {
    const printContent = `
      <!DOCTYPE html>
      <html>
      <head>
        <meta charset="UTF-8">
        <title>${exam} Mock Test Solutions</title>
        <style>
          @import url('https://fonts.googleapis.com/css2?family=STIX+Two+Math&display=swap');
          
          body {
            font-family: Arial, sans-serif;
            margin: 20px;
            color: #000;
          }
          
          h1 {
            color: #2196F3;
            border-bottom: 3px solid #2196F3;
            padding-bottom: 10px;
          }
          
          .ai-badge {
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
            color: white;
            padding: 8px 16px;
            border-radius: 20px;
            display: inline-block;
            margin-bottom: 20px;
            font-size: 14px;
          }
          
          .header {
            margin-bottom: 30px;
          }
          
          .question-card {
            border: 2px solid #ddd;
            padding: 20px;
            margin: 20px 0;
            border-radius: 8px;
            page-break-inside: avoid;
          }
          
          .question-number {
            font-size: 20px;
            font-weight: bold;
            color: #2196F3;
            margin-bottom: 10px;
          }
          
          .concept-badge {
            background: #E3F2FD;
            color: #1565C0;
            padding: 4px 12px;
            border-radius: 12px;
            font-size: 12px;
            display: inline-block;
            margin-left: 10px;
          }
          
          .question-text {
            font-size: 16px;
            margin: 15px 0;
            font-weight: 500;
            font-family: 'STIX Two Math', 'Cambria Math', serif;
            line-height: 1.6;
          }
          
          .correct-answer {
            background: #4CAF50;
            color: white;
            padding: 8px 15px;
            border-radius: 5px;
            display: inline-block;
            margin: 10px 0;
            font-weight: bold;
          }
          
          .section-title {
            font-weight: bold;
            color: #333;
            margin-top: 15px;
            margin-bottom: 8px;
            font-size: 16px;
          }
          
          .solution {
            line-height: 1.8;
            margin: 10px 0;
            white-space: pre-wrap;
            font-family: 'STIX Two Math', 'Cambria Math', serif;
          }
          
          .concept {
            background: #FFF3CD;
            border-left: 4px solid #FFC107;
            padding: 12px;
            margin: 15px 0;
            border-radius: 4px;
          }
          
          @media print {
            body { margin: 15mm; }
            .question-card { page-break-inside: avoid; }
            button { display: none; }
          }
        </style>
      </head>
      <body>
        <div class="header">
          <h1>${exam} Mock Test - Detailed Solutions</h1>
          <div class="ai-badge">✨ Generated by AI Vision</div>
          <p>Generated: ${new Date().toLocaleString()}</p>
          <p>Total Questions: ${solutions.length}</p>
        </div>
        
        ${solutions.map(solution => `
          <div class="question-card">
            <div class="question-number">
              Question ${solution.questionNumber}
              ${(solution.concept || solution.keyConcept) ? `<span class="concept-badge">${solution.concept || solution.keyConcept}</span>` : ''}
            </div>
            
            ${(solution.question || solution.questionText) ? `
              <div class="question-text">${solution.question || solution.questionText}</div>
            ` : ''}
            
            <div class="correct-answer">
              ✓ Correct Answer: ${solution.correctAnswer}
            </div>
            
            <div class="section-title">Step-by-Step Solution:</div>
            <div class="solution">${solution.solution}</div>
            
            ${(solution.concept || solution.keyConcept) ? `
              <div class="concept">
                💡 Key Concept: ${solution.concept || solution.keyConcept}
              </div>
            ` : ''}
          </div>
        `).join('')}
        
      </body>
      </html>
    `;
    
    const printWindow = window.open('', '_blank', 'width=800,height=600');
    
    if (printWindow) {
      printWindow.document.open();
      printWindow.document.write(printContent);
      printWindow.document.close();
      printWindow.onload = () => {
        printWindow.print();
      };
    } else {
      alert('Please allow popups to download PDF. Or use Ctrl+P to print this page.');
    }
  };

  return (
    <div className="space-y-6 animate-fade-in">
      {/* AI Vision Badge */}
      <div className="bg-gradient-to-r from-primary/10 to-secondary/10 border border-primary/20 rounded-xl p-3 text-center">
        <div className="flex items-center justify-center gap-2">
          <Sparkles className="w-4 h-4 text-primary" />
          <p className="text-sm font-medium text-foreground">
            Powered by AI Vision - 100% Accurate Math Notation
          </p>
        </div>
      </div>

      <div className="text-center mb-6">
        <h2 className="text-xl font-bold text-foreground">
          Solutions - {exam} Mock Test
        </h2>
        <p className="text-sm text-muted-foreground mt-1">
          {solutions.length} questions analyzed
        </p>
      </div>

      <Accordion type="single" collapsible className="space-y-3">
        {solutions.map((solution, index) => (
          <AccordionItem
            key={index}
            value={`question-${solution.questionNumber}`}
            className="border rounded-xl overflow-hidden bg-card shadow-sm"
          >
            <AccordionTrigger className="px-4 py-3 hover:no-underline hover:bg-muted/50">
              <div className="flex items-center gap-3 text-left flex-1">
                <div className="w-8 h-8 rounded-full bg-primary/10 flex items-center justify-center text-sm font-bold text-primary">
                  {solution.questionNumber}
                </div>
                <div className="flex-1">
                  <div className="flex items-center gap-2 flex-wrap">
                    <span className="font-semibold text-foreground">
                      Question {solution.questionNumber}
                    </span>
                    {(solution.concept || solution.keyConcept || solution.topic) && (
                      <Badge variant="secondary" className="text-xs">
                        {solution.concept || solution.keyConcept || solution.topic}
                      </Badge>
                    )}
                  </div>
                </div>
              </div>
            </AccordionTrigger>
            <AccordionContent className="px-4 pb-4">
              <div className="space-y-4 pt-2">
                {/* Question Text */}
                {(solution.question || solution.questionText) && (
                  <div className="p-3 bg-muted/50 rounded-lg">
                    <p className="text-sm font-medium text-muted-foreground mb-1">
                      Question:
                    </p>
                    <MathText 
                      text={solution.question || solution.questionText || ""} 
                      className="text-foreground leading-relaxed"
                    />
                  </div>
                )}

                {/* Correct Answer */}
                <div className="p-3 bg-secondary/10 rounded-lg border border-secondary/20">
                  <p className="text-sm font-medium text-secondary mb-1">
                    ✓ Correct Answer:
                  </p>
                  <MathText 
                    text={solution.correctAnswer} 
                    className="text-foreground font-semibold text-lg"
                  />
                </div>

                {/* Solution */}
                <div className="p-3 bg-primary/5 rounded-lg border border-primary/10">
                  <p className="text-sm font-medium text-primary mb-2">
                    Step-by-Step Solution:
                  </p>
                  <div 
                    className="text-foreground text-sm whitespace-pre-wrap leading-relaxed"
                    style={{ fontFamily: "'Cambria Math', 'Latin Modern Math', 'STIX Two Math', serif" }}
                  >
                    {solution.solution}
                  </div>
                </div>

                {/* Key Concept */}
                {(solution.concept || solution.keyConcept) && (
                  <div className="p-3 bg-accent/10 rounded-lg border border-accent/20">
                    <p className="text-sm font-medium text-accent mb-1">
                      💡 Key Concept:
                    </p>
                    <p className="text-foreground text-sm">
                      {solution.concept || solution.keyConcept}
                    </p>
                  </div>
                )}
              </div>
            </AccordionContent>
          </AccordionItem>
        ))}
      </Accordion>

      <div className="flex flex-col sm:flex-row gap-3 pt-4">
        <Button
          onClick={handleDownloadPdf}
          className="flex-1 bg-secondary hover:bg-secondary/90 text-secondary-foreground"
        >
          <Download className="w-4 h-4 mr-2" />
          📄 Download PDF Report
        </Button>
        <Button
          variant="outline"
          onClick={onReset}
          className="flex-1"
        >
          <RefreshCw className="w-4 h-4 mr-2" />
          🔄 Analyze Another Test
        </Button>
      </div>
    </div>
  );
};

export default SolutionsResult;
