import { Card, CardContent } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Alert, AlertDescription } from "@/components/ui/alert";
import {
  Download,
  RefreshCw,
  Home,
  CheckCircle,
  BarChart3,
  Target,
  Calendar,
  Star,
  AlertTriangle,
  PartyPopper
} from "lucide-react";
import { ChoiceFillingFormData } from "@/pages/ChoiceFilling";

interface ApiResponse {
  success: boolean;
  studentInfo: Record<string, unknown>;
  reports: {
    fullResponse: string;
  };
  timestamp: string;
}

interface ChoiceFillingResultsProps {
  response: ApiResponse;
  formData: ChoiceFillingFormData;
  onReset: () => void;
  onGoHome: () => void;
}

const ChoiceFillingResults = ({
  response,
  formData,
  onReset,
  onGoHome
}: ChoiceFillingResultsProps) => {
  const handleDownloadPdf = () => {
    const reportContent = response.reports.fullResponse;
    
    const htmlContent = `
      <!DOCTYPE html>
      <html lang="en">
      <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>JoSAA Counselling Strategy - EduGuide</title>
        <style>
          * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
          }
          body {
            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
            line-height: 1.6;
            color: #1a1a2e;
            padding: 40px;
            max-width: 900px;
            margin: 0 auto;
          }
          .header {
            text-align: center;
            margin-bottom: 40px;
            padding-bottom: 20px;
            border-bottom: 3px solid #2196F3;
          }
          .header h1 {
            color: #2196F3;
            font-size: 28px;
            margin-bottom: 10px;
          }
          .header .subtitle {
            color: #666;
            font-size: 14px;
          }
          .student-info {
            background: #f8f9fa;
            padding: 20px;
            border-radius: 10px;
            margin-bottom: 30px;
          }
          .student-info h2 {
            color: #2196F3;
            font-size: 18px;
            margin-bottom: 15px;
          }
          .info-grid {
            display: grid;
            grid-template-columns: repeat(2, 1fr);
            gap: 10px;
          }
          .info-item {
            font-size: 14px;
          }
          .info-item strong {
            color: #333;
          }
          .report-content {
            white-space: pre-wrap;
            font-size: 14px;
            line-height: 1.8;
          }
          .report-content h2,
          .report-content h3 {
            color: #2196F3;
            margin-top: 25px;
            margin-bottom: 15px;
          }
          .disclaimer {
            background: #fff3cd;
            border: 1px solid #ffc107;
            padding: 15px;
            border-radius: 8px;
            margin-top: 30px;
            font-size: 13px;
            color: #856404;
          }
          .footer {
            text-align: center;
            margin-top: 40px;
            padding-top: 20px;
            border-top: 1px solid #ddd;
            color: #666;
            font-size: 12px;
          }
          @media print {
            body {
              padding: 20px;
            }
            .disclaimer {
              break-inside: avoid;
            }
          }
        </style>
      </head>
      <body>
        <div class="header">
          <h1>🎓 JoSAA Counselling Strategy Report</h1>
          <p class="subtitle">Generated by EduGuide AI | ${new Date().toLocaleDateString('en-IN', { 
            year: 'numeric', 
            month: 'long', 
            day: 'numeric' 
          })}</p>
        </div>

        <div class="student-info">
          <h2>📋 Student Profile</h2>
          <div class="info-grid">
            <div class="info-item"><strong>JEE Main AIR:</strong> ${formData.mainRank}</div>
            ${formData.advancedRank ? `<div class="info-item"><strong>JEE Advanced AIR:</strong> ${formData.advancedRank}</div>` : ''}
            <div class="info-item"><strong>Category:</strong> ${formData.category}</div>
            <div class="info-item"><strong>Gender:</strong> ${formData.gender}</div>
            <div class="info-item"><strong>Home State:</strong> ${formData.homeState}</div>
            <div class="info-item"><strong>Strategy:</strong> ${formData.strategy}</div>
          </div>
          <div style="margin-top: 15px;">
            <div class="info-item"><strong>Preferred Branches:</strong> ${formData.branches.join(', ')}</div>
            <div class="info-item"><strong>College Types:</strong> ${formData.collegeTypes.join(', ')}</div>
          </div>
        </div>

        <div class="report-content">
          ${reportContent.replace(/\n/g, '<br>')}
        </div>

        <div class="disclaimer">
          <strong>⚠️ Important Disclaimer:</strong><br>
          This guidance is based on previous years' cutoff trends (2023-24 data). Actual cutoffs may vary. 
          Always verify from official JoSAA website (josaa.nic.in) before final submission.
        </div>

        <div class="footer">
          <p>Generated by EduGuide - Your AI Companion for Exam Success</p>
          <p>© ${new Date().getFullYear()} EduGuide. For guidance purposes only.</p>
        </div>
      </body>
      </html>
    `;

    const printWindow = window.open('', '_blank');
    if (printWindow) {
      printWindow.document.write(htmlContent);
      printWindow.document.close();
      setTimeout(() => {
        printWindow.print();
      }, 500);
    }
  };

  const stats = [
    { icon: <BarChart3 className="w-5 h-5" />, label: "Total Choices", value: "100" },
    { icon: <Target className="w-5 h-5" />, label: "Strategy", value: formData.strategy },
    { icon: <Calendar className="w-5 h-5" />, label: "Data Year", value: "2023-24" },
    { icon: <Star className="w-5 h-5" />, label: "Based on", value: "Official cutoffs" }
  ];

  return (
    <div className="space-y-4 animate-fade-in">
      {/* Success Banner */}
      <Card className="bg-secondary/10 border-secondary/30">
        <CardContent className="pt-6 pb-6 text-center">
          <div className="inline-flex items-center justify-center w-16 h-16 rounded-full bg-secondary/20 mb-4">
            <PartyPopper className="w-8 h-8 text-secondary" />
          </div>
          <h2 className="text-xl font-bold text-foreground mb-2">
            🎉 Your Personalized Strategy is Ready!
          </h2>
          <p className="text-sm text-muted-foreground">
            JoSAA Counselling Guide for JEE Main AIR {formData.mainRank}
          </p>
        </CardContent>
      </Card>

      {/* Summary Card */}
      <Card>
        <CardContent className="pt-6">
          <h3 className="font-semibold mb-4 text-lg">What's Included</h3>
          <div className="space-y-3">
            {[
              "100 college-branch combinations analyzed",
              "Includes Dream, Target, and Safe strategies",
              "Complete counselling guide with process explained",
              "Detailed strategy rationale and risk analysis"
            ].map((item, index) => (
              <div key={index} className="flex items-center gap-3">
                <CheckCircle className="w-5 h-5 text-secondary flex-shrink-0" />
                <span className="text-sm">{item}</span>
              </div>
            ))}
          </div>
        </CardContent>
      </Card>

      {/* Download Button */}
      <Button
        onClick={handleDownloadPdf}
        size="lg"
        className="w-full bg-secondary hover:bg-secondary/90 text-secondary-foreground h-14 text-base"
      >
        <Download className="w-5 h-5 mr-2" />
        Download Complete Counselling Report (PDF)
      </Button>

      {/* Stats Grid */}
      <div className="grid grid-cols-2 gap-3">
        {stats.map((stat, index) => (
          <Card key={index} className="bg-muted/30">
            <CardContent className="p-4 text-center">
              <div className="inline-flex items-center justify-center w-10 h-10 rounded-full bg-primary/10 text-primary mb-2">
                {stat.icon}
              </div>
              <p className="text-xs text-muted-foreground">{stat.label}</p>
              <p className="font-semibold text-sm">{stat.value}</p>
            </CardContent>
          </Card>
        ))}
      </div>

      {/* Disclaimer */}
      <Alert className="bg-accent/10 border-accent/30">
        <AlertTriangle className="h-4 w-4 text-accent" />
        <AlertDescription className="text-sm">
          <strong>Important:</strong> This guidance is based on previous years' cutoff trends (2023-24 data). 
          Actual cutoffs may vary. Always verify from official{" "}
          <a
            href="https://josaa.nic.in"
            target="_blank"
            rel="noopener noreferrer"
            className="text-primary underline"
          >
            JoSAA website
          </a>{" "}
          before final submission.
        </AlertDescription>
      </Alert>

      {/* Action Buttons */}
      <div className="flex gap-3 pt-2">
        <Button
          variant="outline"
          onClick={onReset}
          className="flex-1"
        >
          <RefreshCw className="w-4 h-4 mr-2" />
          Generate Again
        </Button>
        <Button
          variant="outline"
          onClick={onGoHome}
          className="flex-1"
        >
          <Home className="w-4 h-4 mr-2" />
          Back to Home
        </Button>
      </div>

      {/* Powered By Badge */}
      <div className="text-center pt-4">
        <Badge variant="secondary" className="text-xs">
          ✨ Powered by EduGuide AI
        </Badge>
      </div>
    </div>
  );
};

export default ChoiceFillingResults;
